sudo: required

language: node_js
node_js:
  - "6"
services:
  - docker
before_install:
  - sudo apt-get install -y npm
  - npm install 
install:
  - docker build -t docker_node .
script:
  - ./node_modules/.bin/mocha
    #use curl test this site is correctly executed 
  - docker run -d -p 3000:3000 --name docker_node_run docker_node
  #- curl --retry 10 --retry-delay 5 -v http://localhost:3000
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_EB_DEFAULT_REGION
  app: $AWS_EB_APPLICATION_NAME
  env: $AWS_EB_ENV
  on:
    branch: master