branch-defaults:
  master:
    environment: env-development
    group_suffix: null
global:
  application_name: ci_cd_with_docker_aws
  default_ec2_keyname: null
  default_platform: docker
  default_region: us-west-2
  profile: eb-cli
  sc: git
